### ISSUE TITLE
Code coverage shows under 100%

### ISSUE THREAD

**Issue by jedireza** [jedireza/lab-es6#1]
```bash
$ npm test

> lab-es6@1.0.0 test /projects/lab-es6
> lab -t 100 -S -T ./test/transform.js ./test/src/
  
  .

1 tests complete
Test duration: 7 ms
No global variable leaks detected
Coverage: 85.00% (3/20)
src/index.js missing coverage from file(s):
        src/index.js on line(s): 7, 9, 1
Code coverage below threshold: 85.00 < 100
```

<img width="1388" alt="screen shot 2015-07-21 at 3 16 40 pm" src="https://cloud.githubusercontent.com/assets/979929/8813876/87d704f2-2fbb-11e5-9697-f656f4759fc5.png">

**Comment by jedireza** [comment]
@ldesplat have you run into this before? Seems like the boilerplate from the babel transform is what's causing the coverage to show under 100%.

**Comment by ldesplat** [comment]
This gets you 95% of the way. None of this my own work.

See https://github.com/nlf/lab-babel
and especially https://github.com/nlf/lab-babel/pull/4

So, if you add in your package.json `"lab-babel": "https://github.com/phated/lab-babel.git"`
Then you'll get 95% code coverage.

![screen shot 2015-07-21 at 6 42 38 pm](https://cloud.githubusercontent.com/assets/5972411/8816198/5a0964d0-2fd8-11e5-999c-e8f6b8b2473e.png)

**Comment by jedireza** [comment]
Thanks for sharing those links.
